spring:
  freemarker:
    prefix: view/
    expose-request-attributes: true
  datasource:
    url: jdbc:postgresql://localhost/lexik
    username: lexik
    password: password
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  mail:
    host: smtp.yandex.ru
    username: activation@lexik.me
    password: "!12345678"
    port: 465
    protocol: smtps

upload:
  path: /Users/KhrebtovD/Desktop/uploads

mail:
  debug: true